bb-io/Jira

Apps.Jira/Apps.Jira.csproj
=> Version update

Apps.Jira/Actions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/Models/Requests/AddAttachmentRequest.cs, Apps.Jira/Models/Responses/DownloadAttachmentResponse.cs
=> Updated files

Apps.Jira/Apps.Jira.csproj, Apps.Jira/JiraApplication.cs, Apps.Jira/JiraClient.cs
Bug fixes and minor improvements
=> Categories

Apps.Jira/Apps.Jira.csproj, Apps.Jira/Webhooks/Inputs/OptionalStatusInput.cs, Apps.Jira/Webhooks/IssueWebhooks.cs, README.md
Updated on issue status changed
=> Updated on issue status changed

Apps.Jira/Actions/IssueCommentActions.cs, Apps.Jira/Apps.Jira.csproj
=> Test create comment

Apps.Jira/Actions/IssueCommentActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/Dtos/ErrorDto.cs, Apps.Jira/JiraClient.cs, Apps.Jira/Models/Requests/AddIssueCommentRequest.cs
=> Fix error handling

Apps.Jira/Actions/IssueCustomFieldsActions.cs, Apps.Jira/Apps.Jira.csproj
=> nullcheck and jtoken type handling for custom fields

Apps.Jira/Actions/IssueCustomFieldsActions.cs, Apps.Jira/Apps.Jira.csproj
Custom fields - parsing more types of multi select items
=> custom field try parsing multiple types

Apps.Jira/Actions/DebugActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/Models/Requests/LabelsOptionalInput.cs
=> Removed labels dynamic data source

Apps.Jira/Apps.Jira.csproj, Apps.Jira/DataSourceHandlers/LabelDataHandler.cs, Apps.Jira/Models/Requests/LabelsOptionalInput.cs, Apps.Jira/Webhooks/IssueWebhooks.cs, README.md
Added optional manual and dropdown inputs
=> Added optional manual input to JIRA

Apps.Jira/Actions/IssueActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/Models/Requests/CreateIssueRequest.cs
Added assignee property as non required to json
=> Added assignee property as non required to json

Apps.Jira/Actions/IssueActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/Dtos/IssueDto.cs, Apps.Jira/Dtos/IssueWrapper.cs, Apps.Jira/Models/Requests/UpdateIssueRequest.cs, Apps.Jira/Utils/JiraDocToMarkdownConverter.cs, Apps.Jira/Utils/MarkdownToJiraConverter.cs
Fixed description formatting issue
=> Fixed formatting issue

Apps.Jira/Actions/IssueActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/DataSourceHandlers/FormattingDataSource.cs, Apps.Jira/Dtos/IssueWrapper.cs, Apps.Jira/Models/Requests/AppendDescriptionRequest.cs, Apps.Jira/Utils/JiraDocToMarkdownConverter.cs, Apps.Jira/Utils/MarkdownToJiraConverter.cs, README.md
Added 'Append to issue description' action
=> Added append to issue description action

Apps.Jira/Apps.Jira.csproj, Apps.Jira/Webhooks/IssueWebhooks.cs
Fix issue with Labels (dropdown selection) optional input
=> Fix issue with Labels (dropdown selection) optional input

Apps.Jira/Actions/IssueCustomFieldsActions.cs, Apps.Jira/Apps.Jira.csproj
=> Return null if custom fields are empty instead of throwing exception

Apps.Jira/Actions/IssueCustomFieldsActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/Models/Responses/GetCustomFieldDateResponse.cs
=> Custom field type date getter to return null if min value

Apps.Jira/Apps.Jira.csproj, Apps.Jira/Dtos/IssueDto.cs, Apps.Jira/Dtos/IssueWrapper.cs
=> Minor improvements

Apps.Jira/Actions/IssueActions.cs, Apps.Jira/Actions/SprintAction.cs, Apps.Jira/DataSourceHandlers/BoardDataSourceHandler.cs, Apps.Jira/DataSourceHandlers/SprintDataHandler.cs, Apps.Jira/Dtos/SprintMoveIssueDto.cs, Apps.Jira/JiraClient.cs, Apps.Jira/Models/Requests/GetSprintByDateRequest.cs, Apps.Jira/Models/Requests/MoveIssuesToSprintRequest.cs, Apps.Jira/Models/Responses/BoardsResponse.cs, Apps.Jira/Models/Responses/MoveIssuesToSprintResponse.cs, Apps.Jira/Models/Responses/SprintsResponse.cs
=> Scopes update

Apps.Jira/Actions/IssueActions.cs, Apps.Jira/Actions/SprintAction.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/Models/Requests/MoveIssuesToSprintRequest.cs, Apps.Jira/Models/Responses/MoveIssuesToSprintResponse.cs
=> Scope update

Apps.Jira/Actions/IssueActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/DataSourceHandlers/SprintDataHandler.cs, Apps.Jira/Models/Requests/MoveIssuesToSprintRequest.cs
=> Action move issue to sprint

Apps.Jira/Actions/IssueActions.cs, Apps.Jira/ApplicationConstants.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/DataSourceHandlers/BoardDataSourceHandler.cs, Apps.Jira/DataSourceHandlers/SprintDataHandler.cs, Apps.Jira/JiraClient.cs
=> Fix action MoveIssuesToSprint 

Apps.Jira/Actions/SprintAction.cs, Apps.Jira/ApplicationConstants.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/DataSourceHandlers/BoardDataSourceHandler.cs, Apps.Jira/JiraClient.cs, README.md
Action move issue to sprint and get relevant spint for date
=> Action move issue to sprint and get relevant spint for date

Apps.Jira/Apps.Jira.csproj, Apps.Jira/Webhooks/IssueWebhooks.cs, Tests.Jira/Tests.Jira.csproj
=> Update event On issue created

Apps.Jira/Apps.Jira.csproj, Apps.Jira/Webhooks/Inputs/ProjectIssueInput.cs, Apps.Jira/Webhooks/IssueWebhooks.cs
=> Updated events on issue

Apps.Jira/Apps.Jira.csproj, Apps.Jira/JiraClient.cs, Apps.Jira/JiraPollyPolicies.cs, Tests.Jira/DataSources.cs
=> Added Retry-After policy

Apps.Jira/Actions/IssueCustomFieldsActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/DataSourceHandlers/CustomFields/CustomNumericFieldDataSourceHandler.cs, Apps.Jira/Models/Identifiers/CustomNumericFieldIdentifier.cs, Tests.Jira/DataSources.cs
Added actions add and set custom numeric field
=> Added actions add and set custom numeric field

Apps.Jira/Actions/IssueCustomFieldsActions.cs, Apps.Jira/Apps.Jira.csproj, README.md
=> Updated documentation

Apps.Jira/Apps.Jira.csproj, Apps.Jira/JiraClient.cs, Tests.Jira/DataSources.cs
Added application error handling
=> Added application error handling

Apps.Jira/Actions/IssueCustomFieldsActions.cs, Apps.Jira/Apps.Jira.csproj, Tests.Jira/DataSources.cs
Added action set multiselect field
=> Added action set multiselect field

Apps.Jira/Actions/IssueCustomFieldsActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/Models/Requests/CustomMultiselectFieldInput.cs, Tests.Jira/DataSources.cs
=> Changed input model

Apps.Jira/Actions/IssueCustomFieldsActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/Models/Requests/CustomMultiselectFieldInput.cs, Tests.Jira/DataSources.cs
Changed naming input in action Set custom multiselect field
=> Changed naming input in action Set custom multiselect field

Apps.Jira/Apps.Jira.csproj, Apps.Jira/JiraPollyPolicies.cs
=> Increased retry count

Apps.Jira/Actions/IssueActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/Models/Requests/CreateIssueRequest.cs, Apps.Jira/Models/Requests/UpdateIssueRequest.cs, Tests.Jira/DataSources.cs, Tests.Jira/IssueTests.cs
Added optional input to Create issue and Update issue
=> Added optional input to Create issue and Update issue

Apps.Jira/Apps.Jira.csproj, Apps.Jira/Models/Requests/CreateIssueRequest.cs, Tests.Jira/IssueTests.cs
=> Minor fixes

Apps.Jira/Actions/IssueActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/Dtos/IssueDto.cs, Apps.Jira/JiraClient.cs, Apps.Jira/Models/Requests/CreateIssueRequest.cs, Tests.Jira/DataSources.cs, Tests.Jira/IssueTests.cs
Checking for action 'Get Issue' and error handling for resource validation
=> Checking for action 'Get Issue' and error handling for resource validation

Apps.Jira/Apps.Jira.csproj, Apps.Jira/Utils/JiraDocToMarkdownConverter.cs, Tests.Jira/IssueTests.cs
Modification on ConvertToMarkdown method
=> Modification on ConvertToMarkdown method

Apps.Jira/Actions/IssueCommentActions.cs, Apps.Jira/Apps.Jira.csproj, Tests.Jira/IssueTests.cs
Fixes in action 'Add issue comment'
=> Fixes in action 'Add issue comment'

Apps.Jira/Apps.Jira.csproj, Apps.Jira/JiraPollyPolicies.cs, Tests.Jira/IssueTests.cs
Updated login in Polly policies
=> Updated login in Polly policies

Apps.Jira/Actions/SprintAction.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/JiraClient.cs, Apps.Jira/Models/Responses/PaginationResponse.cs, Tests.Jira/DataSources.cs
Added pagination to action 'Get relevant sprint for date'
=> Added pagination to action 'Get relevant sprint for date'

Apps.Jira/Actions/IssueCustomFieldsActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/Models/Requests/RichTextMarksRequest.cs
Updated custom rich text field to allow marks and link URL
=> Updated custom rich text field to allow marks and link URL

Apps.Jira/Actions/IssueActions.cs, Apps.Jira/Apps.Jira.csproj, Apps.Jira/DataSourceHandlers/FixVersionDataHandler.cs, Apps.Jira/Dtos/FixVersionDto.cs, Apps.Jira/Models/Identifiers/ProjectIdentifier.cs, Apps.Jira/Models/Requests/ListRecentlyCreatedIssuesRequest.cs, Tests.Jira/DataSources.cs, Tests.Jira/IssueTests.cs
Add label and fix version filters to 'List recently created issues' action
=> Add label and fix version filters to 'List recently created issues' action

Apps.Jira/Apps.Jira.csproj, Apps.Jira/DataSourceHandlers/IssueDataSourceHandler.cs, Apps.Jira/Models/Responses/ProjectSearchResponse.cs
=> Fixes in Issue data handler
